services:
  oic-backend:
    container_name: oic-backend
    restart: always
    environment:
      - server.port=${APP_SERVER_PORT}
    ports:
      - '9090:9090'
    expose:
      - '9090'
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network